#!/bin/sh
# This script goes into ~/.local/bin

# Setting dwm as current Desktop for env
#export XDG_SESSION_DESKTOP='dwm'
#export XDG_CURRENT_DESKTOP='dwm'

# Clear old screen temp and set to 5000 the actual
gammastep -x -m randr && gammastep -O 5000 -m randr

# Set wallpaper with xwallpaper tool
x-wset --zoom ~/Pix/somepicture
